export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as Recovery } from './Recovery'
export { default as Vehicles } from './Vehicles'
export { default as NewVehicle } from './NewVehicle'
export { default as VehicleInfo } from './vehicleInfo/'
export { default as EditVehicle } from './EditVehicle'