export interface IVehicle {
    id: string,
    ano: number,
    arCondicionado: boolean,
    cambio: string,
    cidade: string,
    cilindradas: string,
    clientId: string,
    dataKms: string,
    descricao: string,
    finalPlaca: string,
    kms: number,
    marca: string,
    modelo: string,
    preco: string,
    tipoCombustivel: string,
    tipoVeiculo: string,
    uf: string,
    fotosUrl: string[]
}